config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/index'
  get 'pages/home'

post 'pins/:id/like', as: 'pins_like', to: 'pins#like'

  #get 'home', to: 'pages#index'
  #get 'pines', to: 'pins#pines'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins

  root 'pins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :pin
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :pins

def avatar
    type = ['men', 'women'].sample
    number = (1..99).to_a.sample
    "https://randomuser.me/api/portraits/#{type}/#{number}.jpg"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def home
  	@pins = Pin.all
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
before_action :set_pin, only: [:like, :destroy, :edit, :update, :show]
  def index
  	@pins = Pin.all
  end

  def like
  	Like.create(pin: @pin, user: current_user)
  	redirect_to pins_path
  end

  def destroy
  	@pin.likes.delete_all
  	@pin.delete
  	redirect_to pins_path
  end

  def show

  end

  def update
  	@pin.update(pins_params)
  	redirect_to pins_path
  end

  def set_pin
  	@pin = Pin.find(params[:id])
  end	

  def new
  	@pin = Pin.new
  end

  def edit
  end

  def create
  	@pin = Pin.new(pins_params)
  	@pin.user = current_user
  	if @pin.save!
  		redirect_to pins_path  		
  	else
  		redirect new_pin_path, notice: 'Error desconocido'
  	end
  end

  private

	  def pins_params
	  	params.require(:pin).permit(:name, :desc, :photo)
	  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= favicon_link_tag 'favicon.ico', :width=>"55", :height=>"30" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <hr />
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
  	<% @pins.each do |pin| %>  	
     <%= render 'pages/card', pin:pin %>
     <br>
    <% end %>    
  </div>
</div>

app/views/pages/index.html.erb
<h1>Pins</h1>
<h2>Algo estara aqui pronto jaja</h2>

app/views/pins/_card.html.erb
<div class="col-sm">
      <div class="card" style="width: 18rem;">
      	<%= link_to pin_path(pin) do %>
		  <img src="<%= pin.photo %>" class="card-img-top" alt="..."> <!--  -->
		<% end %>
  <div class="card-body">
    <h5 class="card-title"><%= pin.name  %></h5>
    <p class="card-text"><%= pin.desc  %></p>
    <p class="card-text">Likes : <%= pin.likes.count  %></p>
    <a href="/pins/<%= pin.id %>/like" 
       data-method="POST" 
       class="btn btn-primary">Me Gusta</a>

	<% if pin.user == current_user %>
	    <%= link_to 'Editar', edit_pin_path(pin), class: 'btn btn-primary' %>
    	<%= link_to 'Borrar', pin_path(pin), method: 'DELETE', class: 'btn btn-primary' %>		
	<% end %>
  </div>
</div>
    </div>

app/views/pins/edit.html.erb
<%= form_with model: @pin do |f| %>
<div class="form-group">
  <%= f.text_field :name, placeholder: 'Nombre' %>
</div>
<div class="form-group">  
  <%= f.text_field :desc, placeholder: 'Descripción' %>
</div>
<div class="form-group">  
  <%= f.text_field :photo, placeholder: 'URL de la Foto' %>
</div>
<div class="form-group">  
  <%= f.submit 'Guardar Pin', class: 'btn btn-primary' %>
</div>  
<% end %>

app/views/pins/index.html.erb
<div class="container">
  <div class="row">
  	<% @pins.each do |pin| %>  	
     <%= render 'pins/card', pin:pin %>
     <br>
    <% end %>    
  </div>
</div>

app/views/pins/new.html.erb
<%= form_with model: @pin do |f| %>
<div class="form-group">
  <%= f.text_field :name, placeholder: 'Nombre' %>
</div>
<div class="form-group">  
  <%= f.text_field :desc, placeholder: 'Descripción' %>
</div>
<div class="form-group">  
  <%= f.text_field :photo, placeholder: 'URL de la Foto' %>
</div>
<div class="form-group">  
  <%= f.submit 'Crear Pin', class: 'btn btn-primary' %>
</div>  
<% end %>

app/views/pins/pines.html.erb
<h1>Pins#pines</h1>
<p>Find me in app/views/pins/pines.html.erb</p>

app/views/pins/show.html.erb
<%= render 'pins/card', pin: @pin %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <%= link_to pins_path do %> 
  <!-- LOGO CENTRAL -->
    <%= image_tag asset_path('logo_pinterest.png'), class: 'img-custom' %>
  <% end %>

  <!-- MOBILE : esto para funcione el resposivo y se combierta en boton cuando sea pequeña la pantalla-->
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  

  <div class="collapse navbar-collapse" id="collapsibleNavbar" id="navbarcentral">

    <!-- FORMULARIO DE BUSQUEDA --> 
    <form class="form-inline my-3 my-lg-0 menubarra" >
      <input class="form-control menubarra"  type="search" placeholder="Buscar" aria-label="Search">
    </form>

    <ul class="nav navbar-nav navbar-right">

      <% if current_user.nil? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Ingreso</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Registro</a>
        </li>
      <% else %>
      <%= current_user.email %>
      <%= image_tag current_user.avatar, class: 'img-fluid img-custom img-circle' %><!-- img-custom -->
        <li class="nav-item">
          <a class="nav-link" href="<%= new_pin_path %>">Nuevo Pin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">Salir</a>
        </li>  
      <% end %> 
    </ul>
  </div> 
</nav>